### ISSUE TITLE
list_following 抛出类型错误 TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Ensuperb** [OlafZhang/bilib#1]
>>> bilib.list_following(uid=163637592,page=1,step=20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Desktop\bilib\bilib.py", line 1589, in list_following
    raw = result["data"]["list"][int(i)]
TypeError: 'NoneType' object is not subscriptable

**Comment by OlafZhang** [comment]
已通过在bilib.py的1576行中减少一个传参参数（order_type=attention）修复此问题，谢谢！
Fixed by delete a parameter in Line 1576 from bilib.py (order_type=attention), thanks!

**Comment by Ensuperb** [comment]
成功，感谢作者第一时间到达现场。
