### ISSUE TITLE
文档小细节补充

### ISSUE THREAD

**Issue by lb-chc** [OlafZhang/bilib#3]
对于“video_info(id_input)”的ctime参数，文档里标为“未知参数” <img alt="屏幕快照 2021-11-08 下午1 09 11" width="494" src="https://user-images.githubusercontent.com/69136546/140687457-e050ad7d-5a73-4707-869d-e82ec72ff888.png">

我在这个[项目](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/info.md)里找到了解释

<img alt="屏幕快照 2021-11-08 下午1 05 25" width="741" src="https://user-images.githubusercontent.com/69136546/140687277-1cd451e2-e651-4ed8-b57a-02cce886406c.png">

**Comment by lb-chc** [comment]
对于“video_info(id_input)”的ctime参数，文档里标为“未知参数”
<img width="494" alt="屏幕快照 2021-11-08 下午1 09 11" src="https://user-images.githubusercontent.com/69136546/140687457-e050ad7d-5a73-4707-869d-e82ec72ff888.png">

我在这个[项目](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/info.md)里找到了解释

<img alt="屏幕快照 2021-11-08 下午1 05 25" width="741" src="https://user-images.githubusercontent.com/69136546/140687277-1cd451e2-e651-4ed8-b57a-02cce886406c.png">

**Comment by lb-chc** [comment]
另外，video_info(id_input)中是不是没有每分P名称啊......
之后要不要再试试获取用户收藏夹 (๑✦ˑ̫✦)✨

**Comment by OlafZhang** [comment]
OK，来回答你的问题
1.感谢提醒，那这样put_time就是审核成功后投递到b站的时间了，我会在下一次pull前修改readme
2.可能原API是没有的，以我的性格如果找的到这个选项我是肯定会加分P名称的，我今天下午再看看
3.获取用户收藏夹考虑一下吧，毕竟已经做了获取投稿了，这个功能实现起来也不算很难
如果还有什么问题的话可以继续问，没事的话就关一下issue吧👻

**Comment by OlafZhang** [comment]
确认了一下，多分p和单分p都会显示分P名称，readme已经补充
![Uploading 屏幕截图 2021-11-10 134835.jpg…]()
（如果我的蓝灯没问题的话）

**Comment by OlafZhang** [comment]
确认了一下，多分p和单分p都会显示分P名称，readme已经补充
（如果我的蓝灯没问题的话）
![屏幕截图 2021-11-10 134835](https://user-images.githubusercontent.com/55549042/141062237-2cb72055-2128-4256-95a2-97424428cf0a.png)

**Comment by lb-chc** [comment]
> 确认一下，多分p和单分p都显示分p名称，readme已经补充 （如果我的蓝灯没问题的话） ![截图 2021-11-10 134835](https://user-images.githubusercontent.com/55549042/141062237-2cb72055-2128-4256-95a2-97424428cf0a.png)

感谢回复, 有就好......我只是没在文档里看见, 当时很害怕......(如果用到一半发现和返回值差很多就恐怖了)于是自己把json返回值先了看一遍......就是如下这里, 没有name项, 所以以为没有

<img width="705" alt="屏幕快照 2021-11-11 上午9 58 40" src="https://user-images.githubusercontent.com/69136546/141223541-c8c72afa-c3d0-4aed-81b0-cec8965f1c19.png">

另外现在返回值里有“"is_360": 0,”这样的参数更新了,不过不重要

有没有设置代理的地方?
以后有没有可能爬出历史弹幕呢? 我知道这需要登陆, 现在Cookie是出什么问题了?

爬取评论自带楼中回复好评, 这是否意味着要爬[楼中回复数量]次? 有点担心一个IP撑不住......

还想问一下b站目前对API的反爬措施, 比如每次间间隔多少, 一天总量多少, 爬一条就换随机新UA会不会死的更快 , 需要只在热门时间段爬取来模仿用户行为吗......

像我这种提问式issue是不是应该发完就关? 因为开着issue让维护者难受, 关了一样可以问?

(一个刚刚完成PY Hello World的家伙抛出了一大堆问题 ==)

**Comment by lb-chc** [comment]
另外蓝灯竟然还活着, 要不要试试自建vps v2ray? 也有免费节点网站 或个人搭建的收费“机场”

**Comment by OlafZhang** [comment]
hello

**Comment by OlafZhang** [comment]
1，没有设置代理，会考虑加入
2，Cookie现在目前遇到个问题就是必须手动获取（和自己懒的写），之前用request尝试传入Cookie，但是报CookieJam的错误（好像是这个），现在遇到了解决方案，会在一些方法引入（有些方法没必要用Cookie），还有就是传入Cookie就必须限制UA，这会打破bilib中每次请求UA不同的机制，等有空解决（其实现在bilib更新很随缘了）
3，不需要，你可以参考demo_yui.py
4，目前我摸索到的：反爬频率很难和你说，有时候有意大幅度降低爬取速度也会被报412，被反爬后一般是半小时解除，换UA应该死的快，尤其是带Cookie的情况，会死的更快，会提示账户异常
5，没怎么用过issue，不过按套路来说就是完成issue的问题后就可以关了
6，能提出那么多专业术语的萌新挺少见的，加油
7，我会试一下你说的，自己之前搭过Shadowsock的，但是服务器太贵了。。。
